apiVersion: v1
kind: ConfigMap
metadata:
  name: kc-config
data:
  proxy: "edge"
---
apiVersion: v1
kind: Secret
metadata:
  name: kc-secrets
data:
  username: a2NfYWRtaW4=
  password: a2NfcGFzcw==
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: comment-scaler
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: comment-deployment
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50