steps:
  # build backend
  - name: 'gcr.io/cloud-builders/mvn'
    entrypoint: mvn
    args: ['clean', 'install', '-Dmaven.test.skip=true']
    dir: './backend'
  # build comment-service container image
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/${PROJECT_ID}/comment', './backend/services/comment-service' ]
  # build blog-service container image
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/${PROJECT_ID}/blog', './backend/services/blog-service' ]
  # build gateway-service container image
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/${PROJECT_ID}/gateway', './backend/services/gateway-service' ]
  # push comment-service container image
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'gcr.io/${PROJECT_ID}/comment']
  # push blog-service container image
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'gcr.io/${PROJECT_ID}/blog']
  # push gateway-service container image
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'gcr.io/${PROJECT_ID}/gateway']
  # deploy comment container image
  - name: "gcr.io/cloud-builders/gcloud"
    args: [
      'run',
      'deploy',
      'comment',
      '--image',
      'gcr.io/$PROJECT_ID/feed',
      '--port', '8087',
      '--region', 'europe-west4',
      '--platform', 'managed',
      '--allow-unauthenticated']
  # deploy blog container image
  - name: "gcr.io/cloud-builders/gcloud"
    args: [
      'run',
      'deploy',
      'blog',
      '--image',
      'gcr.io/$PROJECT_ID/blog',
      '--port', '8085',
      '--region', 'europe-west4',
      '--platform', 'managed',
      '--allow-unauthenticated']
  # deploy blog container image
  - name: "gcr.io/cloud-builders/gcloud"
    args: [
      'run',
      'deploy',
      'gateway',
      '--image',
      'gcr.io/$PROJECT_ID/gateway',
      '--port', '8070',
      '--region', 'europe-west4',
      '--platform', 'managed',
      '--allow-unauthenticated']
  
  #   # [Web] build the container image
  # - name: 'gcr.io/cloud-builders/docker'
  #   args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/web', './frontend' ]
  #   # [Web] push the container image
  # - name: 'gcr.io/cloud-builders/docker'
  #   args: [ 'push', 'gcr.io/$PROJECT_ID/web']
  #   # [Web] deploy the container to Cloud Run
  # - name: "gcr.io/cloud-builders/gcloud"
  #   args: [
  #     'run',
  #     'deploy',
  #     'web',
  #     '--image',
  #     'gcr.io/$PROJECT_ID/web',
  #     '--port', '80',
  #     '--region', 'europe-west4',
  #     '--platform', 'managed',
  #     '--allow-unauthenticated']
options:
  logging: CLOUD_LOGGING_ONLY
