steps:
    # build [App] jar packages to be used for the docker containers
  - name: 'gcr.io/cloud-builders/mvn'
    entrypoint: mvn
    args: ['clean', 'install', '-Dmaven.test.skip=true']
    dir: './backend'
   # build [App] container image
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/${PROJECT_ID}/feed', './backend/services/feed-service' ]
    # build [App] container image
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/${PROJECT_ID}/blog', './backend/services/blog-service' ]
   # push [App] container image
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'gcr.io/${PROJECT_ID}/feed']

  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'gcr.io/${PROJECT_ID}/blog']

   # deploy [App] container image
  - name: "gcr.io/cloud-builders/gcloud"
    args: [
      'run',
      'deploy',
      'app',
      '--image',
      'gcr.io/$PROJECT_ID/feed',
      '--port', '8087',
      '--region', 'europe-west4',
      '--platform', 'managed',
      '--allow-unauthenticated']

    # deploy [App] container image
  - name: "gcr.io/cloud-builders/gcloud"
    args: [
      'run',
      'deploy',
      'app',
      '--image',
      'gcr.io/$PROJECT_ID/blog',
      '--port', '8085',
      '--region', 'europe-west4',
      '--platform', 'managed',
      '--allow-unauthenticated']
  
  #   # [Web] build the container image
  # - name: 'gcr.io/cloud-builders/docker'
  #   args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/web', './frontend' ]
  #   # [Web] push the container image
  # - name: 'gcr.io/cloud-builders/docker'
  #   args: [ 'push', 'gcr.io/$PROJECT_ID/web']
  #   # [Web] deploy the container to Cloud Run
  # - name: "gcr.io/cloud-builders/gcloud"
  #   args: [
  #     'run',
  #     'deploy',
  #     'web',
  #     '--image',
  #     'gcr.io/$PROJECT_ID/web',
  #     '--port', '80',
  #     '--region', 'europe-west4',
  #     '--platform', 'managed',
  #     '--allow-unauthenticated']
options:
  logging: CLOUD_LOGGING_ONLY
