steps:
    # build jar packages to be used for the docker containers
  # - name: 'gcr.io/cloud-builders/mvn'
  #   entrypoint: mvn
  #   args: ['clean', 'install', '-Dmaven.test.skip=true']
  #   dir: './backend'
    - name: 'docker/compose:1.19.0'
      args: ['up', '-d']
      dir: './backend'
    # - name: 'gcr.io/cloud-builders/docker'
    # args: ['run --rm -it --hostname rabbitmq -p 15672:15672 -p 5672:5672 rabbitmq:3-management']
  #   # build the container image
  # - name: 'gcr.io/cloud-builders/docker'
  #   args: [ 'build', '-t', 'gcr.io/${PROJECT_ID}/app', './backend/services/feed-service' ]
  #   # push the container image
  # - name: 'gcr.io/cloud-builders/docker'
  #   args: [ 'push', 'gcr.io/${PROJECT_ID}/app']
  #   # deploy the container image
  # - name: "gcr.io/cloud-builders/gcloud"
  #   args: [
  #     'run', 
  #     'deploy', 
  #     'app', 
  #     '--image', 
  #     'gcr.io/$PROJECT_ID/app', 
  #     '--port', '8087',
  #     '--region', 'europe-west4', 
  #     '--platform', 'managed', 
  #     '--allow-unauthenticated']
options:
  logging: CLOUD_LOGGING_ONLY
