steps:
    # [App] build the packages
  - name: 'maven:3-jdk-11'
    entrypoint: mvn
    args: [ 'package', '-Dmaven.test.skip=true', 'gcr.io/compact-window-369312/app', './backend/' ]
    # App
    # [App] build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/compact-window-369312/app', './backend/services/feed-service' ]
options:
  logging: CLOUD_LOGGING_ONLY
    # [App] push the container image
  # - name: 'gcr.io/cloud-builders/docker'
  #   args: [ 'push', 'gcr.io/$PROJECT_ID/app']
  #   # [App] deploy container to Cloud Run
  # - name: "gcr.io/cloud-builders/gcloud"
  #   args: [
  #     'run', 
  #     'deploy', 
  #     'app', 
  #     '--image', 
  #     'gcr.io/$PROJECT_ID/app', 
  #     '--region', 'us-central1', 
  #     '--platform', 'managed', 
  #     '--allow-unauthenticated']
