application:
  title: Comment Service
  version: 1.0

server:
  port: 8087
spring:
  application:
    name: comment-service
  rabbitmq:
    host: ${host_rabbit}
  data:
    mongodb:
      uri: mongodb+srv://admin:admin@cluster0.k5qf3w2.mongodb.net/?retryWrites=true&w=majority
      database: comments
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://34.141.128.86:8080/realms/my_realm
management:
  endpoints:
    web:
      exposure:
        include:
          - prometheus