application:
  title: User Service
  version: 1.0

server:
  port: 8086
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8090/eureka/
  instance:
    prefer-ip-address: true
    hostname: localhost

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/tune_in
    username: root
    password: luck
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          # validated token by keycloak
          issuer-uri: http://localhost:8080/realms/my_realm

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always